import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import type { Profile } from "../types.js";
import { readProxyConfig } from "../proxy/config.js";
import { reserveProxyPortAsync } from "../proxy/instance-manager.js";
import * as logger from "../logger.js";

const CODEX_HOME = process.env.CODEX_HOME || path.join(os.homedir(), ".codex");
export const CODEX_CONFIG_FILE = path.join(CODEX_HOME, "config.toml");

export function getNativeProfilePath(name: string): string {
  return path.join(CODEX_HOME, `${name}.config.toml`);
}

export function escapeTomlString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function toTomlArray(values: string[]): string {
  const escaped = values.map((v) => `"${escapeTomlString(v)}"`);
  return `[${escaped.join(", ")}]`;
}

/**
 * Generate a default full base configuration for Codex. There is no separate
 * base config.toml in the codex-hub model; each profile file is self-contained
 * and config.toml is a symlink to the active profile.
 */
export function generateDefaultBaseConfig(): string {
  const home = os.homedir();
  const codexHome = CODEX_HOME;
  const chatgptApp = "/Applications/ChatGPT.app";
  const cuaNode = `${chatgptApp}/Contents/Resources/cua_node`;
  const codexCli = `${chatgptApp}/Contents/Resources/codex`;
  const computerUseApp = `${codexHome}/computer-use/Codex Computer Use.app`;
  const computerUseBinary = `${computerUseApp}/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient`;

  return [
    `theme = "Catppuccin Latte"`,
    "",
    `notify = ${toTomlArray([computerUseBinary, "turn-ended"])}`,
    "",
    "[mcp_servers.node_repl]",
    "args = []",
    `command = "${escapeTomlString(`${cuaNode}/bin/node_repl`)}"`,
    "startup_timeout_sec = 120",
    "",
    "[mcp_servers.node_repl.env]",
    `NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"`,
    `NODE_REPL_NODE_MODULE_DIRS = "${escapeTomlString(`${cuaNode}/lib/node_modules`)}"`,
    `NODE_REPL_NODE_PATH = "${escapeTomlString(`${cuaNode}/bin/node`)}"`,
    `NODE_REPL_TRUSTED_CODE_PATHS = "${escapeTomlString(`${codexHome}:${cuaNode}/lib/node_modules`)}"`,
    `CODEX_HOME = "${escapeTomlString(codexHome)}"`,
    `NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "e7fc907079d6797973cb63f97d2562c965aad8d33f52fb726005bf6702f30afc"`,
    `BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"`,
    `NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."`,
    `NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."`,
    `NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."`,
    `BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"`,
    `BROWSER_USE_CODEX_APP_VERSION = "26.803.81509"`,
    `CODEX_CLI_PATH = "${escapeTomlString(codexCli)}"`,
    "",
    "[mcp_servers.computer-use]",
    `command = "${escapeTomlString(`./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient`)}"`,
    `args = ["mcp"]`,
    `cwd = "."`,
    "enabled = false",
    "",
    "[shell_environment_policy.set]",
    `BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"`,
    `NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "e7fc907079d6797973cb63f97d2562c965aad8d33f52fb726005bf6702f30afc"`,
    `NODE_REPL_TRUSTED_CODE_PATHS = "${escapeTomlString(`${codexHome}:${cuaNode}/lib/node_modules`)}"`,
    "",
    "[features]",
    "js_repl = false",
    "",
    "[marketplaces.openai-bundled]",
    `last_updated = "${new Date().toISOString()}"`,
    `source_type = "local"`,
    `source = "${escapeTomlString(`${codexHome}/.tmp/bundled-marketplaces/openai-bundled`)}"`,
    "",
  ].join("\n");
}

export function generateNativeProfileContent(
  name: string,
  data: {
    model?: string;
    modelProvider: string;
    openaiBaseUrl: string;
  },
): string {
  const lines: string[] = [
    `# Generated by codex-hub for profile "${escapeTomlString(name)}". Do not edit manually.`,
    `# codex-hub routes this profile through its local provider proxy.`,
    `model_provider = "${escapeTomlString(data.modelProvider)}"`,
    `openai_base_url = "${escapeTomlString(data.openaiBaseUrl)}"`,
  ];
  if (data.model) {
    lines.push(`model = "${escapeTomlString(data.model)}"`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Build a full profile config by taking a base TOML string and injecting the
 * codex-hub proxy settings at the top. Because we rewrite the whole text,
 * there are no duplicate-key or table-merge issues.
 */
export function buildFullProfileContent(
  name: string,
  profile: Profile,
  proxyBaseUrl: string,
  baseContent: string,
): string {
  const model = profile.models?.[0] || profile.model;

  const profileHeader = [
    `# Generated by codex-hub for profile "${escapeTomlString(name)}". Do not edit manually.`,
    `# codex-hub routes this profile through its local provider proxy.`,
  ].join("\n");

  const profileKeys = [
    `model_provider = "openai"`,
    `openai_base_url = "${escapeTomlString(proxyBaseUrl)}"`,
  ];
  if (model) {
    profileKeys.push(`model = "${escapeTomlString(model)}"`);
  }

  // Strip any existing top-level proxy keys from the base content so we do not
  // end up with duplicates when the base content came from another profile.
  const stripped = stripTopLevelKeys(baseContent, ["model_provider", "openai_base_url", "model"]);

  return `${profileHeader}\n${profileKeys.join("\n")}\n\n${stripped}`.trim() + "\n";
}

/**
 * Remove top-level key assignments from a TOML string. This is a best-effort
 * helper used when rebasing a profile file on another config; it is not a
 * general TOML parser.
 */
function stripTopLevelKeys(content: string, keys: string[]): string {
  const lines = content.split("\n");
  const keyRegexes = keys.map(
    (key) => new RegExp(`^${key}\\s*=\\s*(?:"[^"\\n]*"|'[^'\\n]*'|[^\\n#]+)$`),
  );

  const result: string[] = [];
  let inTable = false;

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();

    if (trimmed === "" || trimmed.startsWith("#")) {
      result.push(rawLine);
      continue;
    }

    if (/^(?:\[[^\]]+\]|\[\[[^\]]+\]\])(?:\s*#.*)?$/.test(trimmed)) {
      inTable = true;
      result.push(rawLine);
      continue;
    }

    if (!inTable && keyRegexes.some((re) => re.test(rawLine))) {
      continue;
    }

    result.push(rawLine);
  }

  // Collapse multiple consecutive blank lines.
  return result
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export async function syncNativeProfile(
  name: string,
  profile: Profile,
  proxyBaseUrl?: string,
): Promise<void> {
  let baseUrl = proxyBaseUrl;
  if (!baseUrl) {
    const port = profile.proxyPort ?? (await reserveProxyPortAsync(name));
    const { listenAddress } = readProxyConfig();
    baseUrl = `http://${listenAddress}:${port}/v1`;
  }

  const filePath = getNativeProfilePath(name);

  // Preserve project trust levels and other Codex-written settings by building
  // on top of the currently active config.toml. If config.toml does not exist
  // yet (e.g. first profile), fall back to the default base template.
  let baseContent = generateDefaultBaseConfig();
  if (fs.existsSync(CODEX_CONFIG_FILE)) {
    baseContent = fs.readFileSync(CODEX_CONFIG_FILE, "utf-8");
  }

  const content = buildFullProfileContent(name, profile, baseUrl, baseContent);
  fs.writeFileSync(filePath, content, "utf-8");
  logger.debug(`synced profile config '${name}' to ${filePath}`);
}

export function removeNativeProfile(name: string): void {
  const filePath = getNativeProfilePath(name);
  try {
    fs.unlinkSync(filePath);
    logger.debug(`removed profile config '${name}' at ${filePath}`);
  } catch (err: any) {
    if (err?.code !== "ENOENT") {
      logger.warn(`failed to remove profile config '${name}'`, err);
    }
  }
}

/**
 * Activate a profile by making ~/.codex/config.toml a symlink to
 * ~/.codex/<name>.config.toml. There is no base config.toml to back up or
 * restore; config.toml exists only as a symlink to the active profile.
 */
export function activateProfileConfig(name: string, profile: Profile, proxyBaseUrl: string): void {
  syncNativeProfile(name, profile, proxyBaseUrl);

  const profilePath = getNativeProfilePath(name);
  const configPath = CODEX_CONFIG_FILE;

  if (fs.existsSync(configPath)) {
    fs.unlinkSync(configPath);
  }

  fs.symlinkSync(profilePath, configPath);
  logger.debug(`activated profile '${name}': ${configPath} -> ${profilePath}`);
}

/**
 * Remove the active symlink if it points to a given profile. There is no base
 * config.toml to restore.
 */
export function deactivateProfileConfig(name: string): void {
  const profilePath = getNativeProfilePath(name);
  const configPath = CODEX_CONFIG_FILE;

  if (fs.existsSync(configPath) && fs.lstatSync(configPath).isSymbolicLink()) {
    const target = fs.readlinkSync(configPath);
    if (target === profilePath) {
      fs.unlinkSync(configPath);
      logger.debug(`deactivated profile '${name}': removed ${configPath}`);
    }
  }
}

export function isValidProfileName(name: string): boolean {
  return /^[a-zA-Z0-9_-]+$/.test(name);
}
