import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import type { Profile } from "../types.js";
import { readProxyConfig } from "../proxy/config.js";
import { reserveProxyPortAsync } from "../proxy/instance-manager.js";
import * as logger from "../logger.js";

const CODEX_HOME = process.env.CODEX_HOME || path.join(os.homedir(), ".codex");
export const CODEX_CONFIG_FILE = path.join(CODEX_HOME, "config.toml");

export function getNativeProfilePath(name: string): string {
  return path.join(CODEX_HOME, `${name}.config.toml`);
}

export function escapeTomlString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function toTomlArray(values: string[]): string {
  const escaped = values.map((v) => `"${escapeTomlString(v)}"`);
  return `[${escaped.join(", ")}]`;
}

/**
 * Generate a default full base configuration for Codex. There is no separate
 * base config.toml in the codex-hub model; each profile file is self-contained
 * and config.toml is a symlink to the active profile.
 */
export function generateDefaultBaseConfig(): string {
  const home = os.homedir();
  const codexHome = CODEX_HOME;
  const chatgptApp = "/Applications/ChatGPT.app";
  const cuaNode = `${chatgptApp}/Contents/Resources/cua_node`;
  const codexCli = `${chatgptApp}/Contents/Resources/codex`;
  const computerUseApp = `${codexHome}/computer-use/Codex Computer Use.app`;
  const computerUseBinary = `${computerUseApp}/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient`;

  return [
    `theme = "Catppuccin Latte"`,
    "",
    `# Context window for kimi-k2.7 (258400 tokens). Auto-compact before hitting the limit.`,
    `model_context_window = 258400`,
    `model_auto_compact_token_limit = 230000`,
    "",
    `notify = ${toTomlArray([computerUseBinary, "turn-ended"])}`,
    "",
    "[mcp_servers.node_repl]",
    "args = []",
    `command = "${escapeTomlString(`${cuaNode}/bin/node_repl`)}"`,
    "startup_timeout_sec = 120",
    "",
    "[mcp_servers.node_repl.env]",
    `NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"`,
    `NODE_REPL_NODE_MODULE_DIRS = "${escapeTomlString(`${cuaNode}/lib/node_modules`)}"`,
    `NODE_REPL_NODE_PATH = "${escapeTomlString(`${cuaNode}/bin/node`)}"`,
    `NODE_REPL_TRUSTED_CODE_PATHS = "${escapeTomlString(`${codexHome}:${cuaNode}/lib/node_modules`)}"`,
    `CODEX_HOME = "${escapeTomlString(codexHome)}"`,
    `NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "e7fc907079d6797973cb63f97d2562c965aad8d33f52fb726005bf6702f30afc"`,
    `BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"`,
    `NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."`,
    `NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."`,
    `NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."`,
    `BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"`,
    `BROWSER_USE_CODEX_APP_VERSION = "26.803.81509"`,
    `CODEX_CLI_PATH = "${escapeTomlString(codexCli)}"`,
    "",
    "[mcp_servers.computer-use]",
    `command = "${escapeTomlString(`./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient`)}"`,
    `args = ["mcp"]`,
    `cwd = "."`,
    "enabled = false",
    "",
    "[shell_environment_policy.set]",
    `BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"`,
    `NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "e7fc907079d6797973cb63f97d2562c965aad8d33f52fb726005bf6702f30afc"`,
    `NODE_REPL_TRUSTED_CODE_PATHS = "${escapeTomlString(`${codexHome}:${cuaNode}/lib/node_modules`)}"`,
    "",
    "[features]",
    "js_repl = false",
    "# Disable the Responses-API-only remote compaction v2 protocol. Chat-Completions",
    "# providers (Kimi/Qianwen) cannot produce the required compaction output item,",
    "# so Codex falls back to the older /responses/compact path or local compaction.",
    "remote_compaction_v2 = false",
    "",
    "[marketplaces.openai-bundled]",
    `last_updated = "${new Date().toISOString()}"`,
    `source_type = "local"`,
    `source = "${escapeTomlString(`${codexHome}/.tmp/bundled-marketplaces/openai-bundled`)}"`,
    "",
  ].join("\n");
}

export function generateNativeProfileContent(
  name: string,
  data: {
    model?: string;
    modelProvider: string;
    openaiBaseUrl: string;
  },
): string {
  const lines: string[] = [
    `# Generated by codex-hub for profile "${escapeTomlString(name)}". Do not edit manually.`,
    `# codex-hub routes this profile through its local provider proxy.`,
    `model_provider = "${escapeTomlString(data.modelProvider)}"`,
    `openai_base_url = "${escapeTomlString(data.openaiBaseUrl)}"`,
  ];
  if (data.model) {
    lines.push(`model = "${escapeTomlString(data.model)}"`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Build a full profile config by taking a base TOML string and injecting the
 * codex-hub proxy settings at the top. Because we rewrite the whole text,
 * there are no duplicate-key or table-merge issues.
 */
export function buildFullProfileContent(
  name: string,
  profile: Profile,
  proxyBaseUrl: string,
  baseContent: string,
): string {
  const model = profile.models?.[0] || profile.model;

  const profileHeader = [
    `# Generated by codex-hub for profile "${escapeTomlString(name)}". Do not edit manually.`,
    `# codex-hub routes this profile through its local provider proxy.`,
  ].join("\n");

  const profileKeys = [
    `model_provider = "openai"`,
    `openai_base_url = "${escapeTomlString(proxyBaseUrl)}"`,
  ];
  if (model) {
    profileKeys.push(`model = "${escapeTomlString(model)}"`);
  }

  // Strip any existing generated profile content from the base content so we
  // do not accumulate duplicate headers or keys when re-syncing a profile.
  const stripped = stripGeneratedProfileContent(baseContent);

  return `${profileHeader}\n${profileKeys.join("\n")}\n\n${stripped}`.trim() + "\n";
}

const GENERATED_HEADER_LINES = [
  "# Generated by codex-hub for profile",
  "# codex-hub routes this profile through its local provider proxy.",
];

function isGeneratedComment(line: string): boolean {
  const trimmed = line.trim();
  return GENERATED_HEADER_LINES.some((prefix) => trimmed.startsWith(prefix));
}

const PROFILE_TOP_LEVEL_KEYS = ["model_provider", "openai_base_url", "model"];

function isProfileTopLevelKey(line: string): boolean {
  const trimmed = line.trim();
  return PROFILE_TOP_LEVEL_KEYS.some((key) =>
    new RegExp(`^${key}\\s*=`).test(trimmed),
  );
}

function isTomlTableHeader(line: string): boolean {
  return /^(?:\[[^\]]+\]|\[\[[^\]]+\]\])(?:\s*#.*)?$/.test(line.trim());
}

/**
 * Remove previously injected codex-hub generated content from a TOML string.
 * This strips the generated comment headers and the top-level profile keys
 * (model_provider, openai_base_url, model) that appear before the first table.
 * It is a best-effort helper, not a general TOML parser.
 */
export function stripGeneratedProfileContent(content: string): string {
  const lines = content.split("\n");
  const result: string[] = [];
  let inTable = false;

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();

    if (trimmed === "" || trimmed.startsWith("#")) {
      if (!isGeneratedComment(rawLine)) {
        result.push(rawLine);
      }
      continue;
    }

    if (isTomlTableHeader(rawLine)) {
      inTable = true;
      result.push(rawLine);
      continue;
    }

    if (!inTable && isProfileTopLevelKey(rawLine)) {
      continue;
    }

    result.push(rawLine);
  }

  // Collapse multiple consecutive blank lines and trim trailing whitespace.
  return result
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export async function syncNativeProfile(
  name: string,
  profile: Profile,
  proxyBaseUrl?: string,
): Promise<void> {
  let baseUrl = proxyBaseUrl;
  if (!baseUrl) {
    const port = profile.proxyPort ?? (await reserveProxyPortAsync(name));
    const { listenAddress } = readProxyConfig();
    baseUrl = `http://${listenAddress}:${port}/v1`;
  }

  const filePath = getNativeProfilePath(name);

  // Preserve project trust levels and other Codex-written settings by building
  // on top of the currently active config.toml. If config.toml does not exist
  // yet (e.g. first profile), fall back to the default base template.
  //
  // We read config.toml even when it is a symlink because it points to the
  // currently active profile and contains the latest user/Codex settings.
  // stripGeneratedProfileContent removes any previously injected profile keys
  // and headers so the result is always clean.
  let baseContent = generateDefaultBaseConfig();
  if (fs.existsSync(CODEX_CONFIG_FILE)) {
    baseContent = fs.readFileSync(CODEX_CONFIG_FILE, "utf-8");
  }

  const content = buildFullProfileContent(name, profile, baseUrl, baseContent);
  fs.writeFileSync(filePath, content, "utf-8");
  logger.debug(`synced profile config '${name}' to ${filePath}`);
}

export function removeNativeProfile(name: string): void {
  const filePath = getNativeProfilePath(name);
  try {
    fs.unlinkSync(filePath);
    logger.debug(`removed profile config '${name}' at ${filePath}`);
  } catch (err: any) {
    if (err?.code !== "ENOENT") {
      logger.warn(`failed to remove profile config '${name}'`, err);
    }
  }
}

/**
 * Activate a profile for the desktop app by writing the profile content
 * directly into ~/.codex/config.toml. The desktop app replaces symlinks with
 * regular files when it saves settings, so we treat config.toml as a writable
 * copy of the active profile. The per-profile file remains the canonical source
 * and is regenerated first to ensure it is up to date.
 */
export function activateProfileConfig(name: string, profile: Profile, proxyBaseUrl: string): void {
  syncNativeProfile(name, profile, proxyBaseUrl);

  const profilePath = getNativeProfilePath(name);
  const configPath = CODEX_CONFIG_FILE;

  // Write config.toml as a copy of the profile file. If config.toml is currently
  // a symlink, replace it with a regular file so the desktop app can rewrite it
  // without breaking profile switching on future launches.
  if (fs.existsSync(configPath) && fs.lstatSync(configPath).isSymbolicLink()) {
    fs.unlinkSync(configPath);
  }

  const content = fs.readFileSync(profilePath, "utf-8");
  fs.writeFileSync(configPath, content, "utf-8");
  logger.debug(`activated profile '${name}': wrote ${configPath} from ${profilePath}`);
}

/**
 * Remove the active config.toml copy if it matches the given profile. This does
 * not delete a user-created base config.toml that was not written by codex-hub.
 */
export function deactivateProfileConfig(name: string): void {
  const profilePath = getNativeProfilePath(name);
  const configPath = CODEX_CONFIG_FILE;

  if (!fs.existsSync(configPath)) {
    return;
  }

  // Only remove config.toml if it is a regular file with the same content as
  // the profile we are deactivating. If it is a symlink or has been edited by
  // the user/desktop app, leave it alone.
  if (fs.lstatSync(configPath).isSymbolicLink()) {
    return;
  }

  try {
    const current = fs.readFileSync(configPath, "utf-8");
    const profile = fs.readFileSync(profilePath, "utf-8");
    if (current === profile) {
      fs.unlinkSync(configPath);
      logger.debug(`deactivated profile '${name}': removed ${configPath}`);
    }
  } catch (err: any) {
    if (err?.code !== "ENOENT") {
      logger.warn(`failed to deactivate profile '${name}'`, err);
    }
  }
}

export function isValidProfileName(name: string): boolean {
  return /^[a-zA-Z0-9_-]+$/.test(name);
}
