import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { describe, it, expect, beforeEach, afterEach } from "vitest";

const TEST_DIR = path.join(os.tmpdir(), `codx-profile-syncer-test-${process.pid}`);
process.env.CODEX_HOME = TEST_DIR;
process.env.CODEX_DIR = TEST_DIR;
process.env.CODX_PROXY_CONFIG_DIR = TEST_DIR;

const profileSyncer = await import("../src/profiles/profile-syncer.js");
const proxyConfig = await import("../src/proxy/config.js");

describe("profile-syncer", () => {
  beforeEach(() => {
    if (fs.existsSync(TEST_DIR)) {
      fs.rmSync(TEST_DIR, { recursive: true, force: true });
    }
    fs.mkdirSync(TEST_DIR, { recursive: true });
  });

  afterEach(() => {
    try {
      fs.rmSync(TEST_DIR, { recursive: true, force: true });
    } catch {
      // ignore
    }
  });

  it("returns the native profile path under CODEX_HOME", () => {
    const filePath = profileSyncer.getNativeProfilePath("kimi-dev");
    expect(filePath).toBe(path.join(TEST_DIR, "kimi-dev.config.toml"));
  });

  it("escapes TOML string special characters", () => {
    expect(profileSyncer.escapeTomlString('say "hello"')).toBe('say \\"hello\\"');
    expect(profileSyncer.escapeTomlString("c:\\path\\to\\file")).toBe("c:\\\\path\\\\to\\\\file");
  });

  it("generateDefaultBaseConfig contains mcp_servers, features, and context limits", () => {
    const content = profileSyncer.generateDefaultBaseConfig();
    expect(content).toContain("[mcp_servers.node_repl]");
    expect(content).toContain("[mcp_servers.computer-use]");
    expect(content).toContain("[features]");
    expect(content).toContain("[marketplaces.openai-bundled]");
    expect(content).toContain('theme = "Catppuccin Latte"');
    expect(content).toContain("model_context_window = 258400");
    expect(content).toContain("model_auto_compact_token_limit = 230000");
    expect(content).toContain("remote_compaction_v2 = false");
  });

  it("builds full profile content with proxy keys at the top", () => {
    const content = profileSyncer.buildFullProfileContent(
      "kimi-dev",
      { model: "kimi-k2-5-coding", provider: "kimi" },
      "http://127.0.0.1:1234/v1",
      "[desktop]\nfollowUpQueueMode = \"queue\"\n",
    );
    expect(content).toContain('# Generated by codex-hub for profile "kimi-dev"');
    expect(content).toContain('model_provider = "openai"');
    expect(content).toContain('openai_base_url = "http://127.0.0.1:1234/v1"');
    expect(content).toContain('model = "kimi-k2-5-coding"');
    expect(content).toContain('[desktop]');
    expect(content.indexOf("model_provider")).toBeLessThan(content.indexOf("[desktop]"));
  });

  it("builds full profile content without a model", () => {
    const content = profileSyncer.buildFullProfileContent(
      "minimal",
      { provider: "qianwen" },
      "http://127.0.0.1:1234/v1",
      "",
    );
    expect(content).toContain('model_provider = "openai"');
    expect(content).toContain('openai_base_url = "http://127.0.0.1:1234/v1"');
    expect(content).not.toContain("model =");
  });

  it("buildFullProfileContent strips existing top-level proxy keys from base", () => {
    const content = profileSyncer.buildFullProfileContent(
      "kimi-dev",
      { model: "kimi-k2-5-coding", provider: "kimi" },
      "http://127.0.0.1:1234/v1",
      'model_provider = "old"\nopenai_base_url = "http://old.example/v1"\n[desktop]\nfollowUpQueueMode = "queue"\n',
    );
    const lines = content.split("\n").filter((line) => line.startsWith("model_provider ="));
    expect(lines.length).toBe(1);
    expect(content).toContain('model_provider = "openai"');
    expect(content).toContain('[desktop]');
  });

  it("syncs native profile file with an explicit URL", () => {
    const filePath = profileSyncer.getNativeProfilePath("kimi-dev");
    profileSyncer.syncNativeProfile("kimi-dev", {
      model: "kimi-k2-5-coding",
      provider: "kimi",
    }, "http://127.0.0.1:1234/v1");

    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain('openai_base_url = "http://127.0.0.1:1234/v1"');
    expect(content).toContain('model = "kimi-k2-5-coding"');
    expect(content).toContain("[mcp_servers.node_repl]");
  });

  it("syncs native profile preserving project nodes from config.toml", () => {
    const configPath = profileSyncer.CODEX_CONFIG_FILE;
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(
      configPath,
      '[projects."/Users/kangtong/work"]\ntrust_level = "trusted"\n',
      "utf-8",
    );

    const filePath = profileSyncer.getNativeProfilePath("kimi-dev");
    profileSyncer.syncNativeProfile("kimi-dev", {
      model: "kimi-k2-5-coding",
      provider: "kimi",
    }, "http://127.0.0.1:1234/v1");

    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain('[projects."/Users/kangtong/work"]');
    expect(content).toContain('trust_level = "trusted"');
    expect(content).toContain('openai_base_url = "http://127.0.0.1:1234/v1"');
  });

  it("syncs native profile deriving URL from persisted proxy port", () => {
    const filePath = profileSyncer.getNativeProfilePath("port-profile");
    const proxyConfigData = proxyConfig.readProxyConfig();
    profileSyncer.syncNativeProfile("port-profile", {
      model: "qwen-max",
      provider: "qianwen",
      proxyPort: 57042,
    });

    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain(`openai_base_url = "http://${proxyConfigData.listenAddress}:57042/v1"`);
  });

  it("reserves a proxy port when syncing without URL or persisted port", async () => {
    const filePath = profileSyncer.getNativeProfilePath("new-profile");
    fs.writeFileSync(
      path.join(TEST_DIR, "profiles.json"),
      JSON.stringify({ profiles: { "new-profile": { provider: "qianwen" } } }, null, 2),
      "utf-8",
    );

    await profileSyncer.syncNativeProfile("new-profile", {
      model: "qwen-max",
      provider: "qianwen",
    });

    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toMatch(/openai_base_url = "http:\/\/127\.0\.0\.1:\d+\/v1"/);
  });

  it("removes a native profile file", () => {
    const filePath = profileSyncer.getNativeProfilePath("to-remove");
    fs.writeFileSync(filePath, "test", "utf-8");
    profileSyncer.removeNativeProfile("to-remove");
    expect(fs.existsSync(filePath)).toBe(false);
  });

  it("removing a missing native profile does not throw", () => {
    expect(() => profileSyncer.removeNativeProfile("missing")).not.toThrow();
  });

  it("activateProfileConfig writes config.toml as a copy of the profile file", () => {
    const configPath = profileSyncer.CODEX_CONFIG_FILE;
    fs.mkdirSync(path.dirname(configPath), { recursive: true });

    profileSyncer.activateProfileConfig("active", { provider: "kimi" }, "http://127.0.0.1:1234/v1");

    expect(fs.lstatSync(configPath).isFile()).toBe(true);
    expect(fs.lstatSync(configPath).isSymbolicLink()).toBe(false);
    const content = fs.readFileSync(configPath, "utf-8");
    expect(content).toContain('# Generated by codex-hub for profile "active"');
    expect(content).toBe(fs.readFileSync(profileSyncer.getNativeProfilePath("active"), "utf-8"));
  });

  it("buildFullProfileContent strips existing generated profile headers and keys from base", () => {
    const base = [
      '# Generated by codex-hub for profile "old". Do not edit manually.',
      "# codex-hub routes this profile through its local provider proxy.",
      'model_provider = "old"',
      'openai_base_url = "http://old.example/v1"',
      'model = "old-model"',
      '',
      '[desktop]',
      'followUpQueueMode = "queue"',
    ].join("\n");

    const content = profileSyncer.buildFullProfileContent(
      "kimi-dev",
      { model: "kimi-k2-5-coding", provider: "kimi" },
      "http://127.0.0.1:1234/v1",
      base,
    );

    expect(content).toContain('# Generated by codex-hub for profile "kimi-dev"');
    expect(content).not.toContain('# Generated by codex-hub for profile "old"');
    const oldRouteComments = content.split("\n").filter((line) =>
      line.trim() === "# codex-hub routes this profile through its local provider proxy.",
    );
    expect(oldRouteComments.length).toBe(1);
    const modelProviderLines = content.split("\n").filter((line) => line.startsWith("model_provider ="));
    expect(modelProviderLines.length).toBe(1);
    expect(content).toContain('[desktop]');
  });

  it("activateProfileConfig replaces an existing symlink with a regular file", () => {
    const configPath = profileSyncer.CODEX_CONFIG_FILE;
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.symlinkSync(profileSyncer.getNativeProfilePath("old"), configPath);
    fs.writeFileSync(profileSyncer.getNativeProfilePath("old"), "old", "utf-8");

    profileSyncer.activateProfileConfig("new", { provider: "kimi" }, "http://127.0.0.1:1234/v1");

    expect(fs.lstatSync(configPath).isFile()).toBe(true);
    expect(fs.lstatSync(configPath).isSymbolicLink()).toBe(false);
    const content = fs.readFileSync(configPath, "utf-8");
    expect(content).toContain('# Generated by codex-hub for profile "new"');
  });

  it("deactivateProfileConfig removes config.toml only when it matches the active profile", () => {
    const configPath = profileSyncer.CODEX_CONFIG_FILE;
    fs.mkdirSync(path.dirname(configPath), { recursive: true });

    profileSyncer.activateProfileConfig("active", { provider: "kimi" }, "http://127.0.0.1:1234/v1");

    profileSyncer.deactivateProfileConfig("other");
    expect(fs.existsSync(configPath)).toBe(true);

    profileSyncer.deactivateProfileConfig("active");
    expect(fs.existsSync(configPath)).toBe(false);
  });
});
